plugins {
    id("dev.kikugie.stonecutter")
}

// The "active" node is the one the IDE indexes, and the one project-unprefixed tasks
// (./gradlew build, ./gradlew runClient) target by default. Change it with:
//   ./gradlew "1.21.1-fabric:stonecutterSwitchTo1.21.1-fabric"
stonecutter active "1.20.1-fabric"

// Merges README.modrinth.md (also used as-is for the Modrinth project description, see the
// modrinth{} block in build.gradle.kts) into README.github.md's <!-- MODRINTH:README -->
// placeholder to produce the final README.md shown on GitHub. Registered on the true root
// project (this script, unlike build.gradle.kts, only applies here) so it exists once,
// independent of which node is active.
tasks.register("generateReadme") {
    group = "documentation"
    description = "Regenerates README.md from README.modrinth.md and README.github.md."

    val modrinthReadme = rootDir.resolve("README.modrinth.md")
    val githubReadme = rootDir.resolve("README.github.md")
    val outputReadme = rootDir.resolve("README.md")

    inputs.files(modrinthReadme, githubReadme)
    outputs.file(outputReadme)

    doLast {
        val placeholder = "<!-- MODRINTH:README -->"
        val base = githubReadme.readText()
        check(placeholder in base) { "${githubReadme.name} is missing the $placeholder placeholder" }
        outputReadme.writeText(
            base.replaceFirst(placeholder, modrinthReadme.readText().trim())
                + "\n<!-- Generated by `./gradlew generateReadme`, do not edit directly. -->\n"
        )
    }
}
